### ISSUE TITLE
运行出错，cuda10.0, torch 1.2.0

### ISSUE THREAD

**Issue by Sohnia** [rogerrojur/tianchi-multi-task-nlp#6]
Traceback (most recent call last):
  File "train.py", line 250, in <module>
    train(batchSize=8, device='cuda:0', lr=10e-4, use_dtp=True, pretrained_model=pretrained_model, tokenizer_model=tokenizer_model, weighted_loss=True)
  File "train.py", line 109, in train
    ocemotion_gold, tnews_kpi, ocnli_kpi, ocemotion_kpi)
  File "/home/zhugc19/tianchi-multi-task-nlp/calculate_loss.py", line 51, in compute_dtp
    if tnews_pred != None:
TypeError: ne() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (Number other)
      didn't match because some of the arguments have invalid types: (NoneType)

**Comment by rogerrojur** [comment]
pytorch 版本 1.6.0
cuda 10.2
你看看readme
